# Lectura de midagri_largo.csv

Datos de producción agrícola mensual por región, año, mes y cultivo (MIDAGRI).

In [1]:
import pandas as pd
from pathlib import Path

csv_path = Path("midagri_largo.csv")
df = pd.read_csv(csv_path)
df

           region  anio  mes_num mes_nombre    cultivo  produccion_mensual
0             Ica  2020        1      Enero   aceituna                0.00
1             Ica  2020        1      Enero        aji              635.00
2             Ica  2020        1      Enero        ajo               12.00
3             Ica  2020        1      Enero  alcachofa                0.00
4             Ica  2020        1      Enero    alfalfa            10684.89
...           ...   ...      ...        ...        ...                 ...
23323  San Martin  2025       12  Diciembre       tuna                0.00
23324  San Martin  2025       12  Diciembre        uva               37.50
23325  San Martin  2025       12  Diciembre       yuca             8748.40
23326  San Martin  2025       12  Diciembre  zanahoria                0.00
23327  San Martin  2025       12  Diciembre    zapallo                0.00

[23328 rows x 6 columns]

In [2]:
print(f"Filas: {len(df):,}  |  Columnas: {len(df.columns)}")
print(f"\nColumnas: {list(df.columns)}")
df.info()

Filas: 23,328  |  Columnas: 6

Columnas: ['region', 'anio', 'mes_num', 'mes_nombre', 'cultivo', 'produccion_mensual']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23328 entries, 0 to 23327
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   region              23328 non-null  object
 1   anio                23328 non-null  int64
 2   mes_num             23328 non-null  int64
 3   mes_nombre          23328 non-null  object
 4   cultivo             23328 non-null  object
 5   produccion_mensual  21473 non-null  float64
dtypes: float64(1), int64(2), object(3)
memory usage: 1.1+ MB

In [3]:
df.head(10)

  region  anio  mes_num mes_nombre            cultivo  produccion_mensual
0    Ica  2020        1      Enero           aceituna                0.00
1    Ica  2020        1      Enero                aji              635.00
2    Ica  2020        1      Enero                ajo               12.00
3    Ica  2020        1      Enero          alcachofa                0.00
4    Ica  2020        1      Enero            alfalfa            10684.89
5    Ica  2020        1      Enero       algodon_rama             1432.79
6    Ica  2020        1      Enero           arandano                0.00
7    Ica  2020        1      Enero      arroz_cascara                0.00
8    Ica  2020        1      Enero  arveja_grano_seco                0.00
9    Ica  2020        1      Enero       arveja_verde                0.00

In [4]:
df.region.value_counts()

region
Ica            3888
Junin          3888
La Libertad    3888
Piura          3888
Puno           3888
San Martin     3888
Name: count, dtype: int64

In [5]:
df.anio.value_counts()

anio
2020    3888
2021    3888
2022    3888
2023    3888
2024    3888
2025    3888
Name: count, dtype: int64

In [6]:
df.mes_nombre.value_counts()

mes_nombre
Enero         1944
Febrero       1944
Marzo         1944
Abril         1944
Mayo          1944
Junio         1944
Julio         1944
Agosto        1944
Septiembre    1944
Octubre       1944
Noviembre     1944
Diciembre     1944
Name: count, dtype: int64

In [7]:
df.produccion_mensual.value_counts()

produccion_mensual
0.00        10864
60.00          27
10.00          26
12.00          25
20.00          22
            ...
33739.50        1
949.60          1
42980.60        1
2325.79         1
8748.40         1
Name: count, Length: 8385, dtype: int64